serverPort = 8443
sslKeyStorePassword = password
sslTrustStorePassword = password
allowedOrigins = https://localhost:8443
loginPassword = password
cookieProperties = ; Path=/;
blockedIpV4s =
blockedIpV6s =
illegalUserAgentContains =
