serverHost = $IP_ADDRESS
# Ports 443 and 8443 will enable SSL
serverPort = 443
sslCertificatePath = $SSL_CERTIFICATE_PATH
sslKeyStorePassword = $KEY_STORE_PASSWORD
keepAliveByDefault = true
allowedOrigins = https://www.gattoslab.dev,https://gattoslab.dev
loginPassword = $LOGIN_PASSWORD
cookieProperties = ; Secure; HttpOnly; Domain=gattoslab.dev; SameSite=Strict; Path=/;
rateLimitAmount = 100
illegalUserAgentContains = $ILLEGAL_USER_AGENT_CONTAINS
privilegedStaticResourcePathPrefix = admin/
diskBasedStaticResourcePathSegment = disk/
observabilityDataRetentionDays = 30
