app:
  database:
    connectionString: ${DB_CONNECTION_STRING}
  session:
    admin:
      apiKey: ${ADMIN_API_KEY}
      cookieAttributes: "=$; Secure; HttpOnly; Domain=gattoslab.dev; SameSite=Strict; Path=/;"
    cors:
      origins: "https://gattoslab.dev,https://www.gattoslab.dev"
    enabled: true
security:
  require-ssl: true
server:
  port: 443
  ssl:
    key-store: "/GattosLab/run/keystore.p12"
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
    keyAlias: "tomcat"
    keyStoreType: "PKCS12"
