app:
  batch:
    poolSize: 5
    terminationWaitPeriod: 10 # Seconds
  logs:
    logsRetention: 7 # Days
    retentionSchedule: "0 0 0 * * *" # Every day at 00:00:00
    squashSchedule: "0 * * * * *" # Every minute
  metrics:
    dumpToDbSchedule: "0 * * * * *" # Every minute
    enabled: true # Affects all types
    requestMetricsRetention: 7 # Days
    retentionSchedule: "0 0 0 * * *" # Every day at 00:00:00
    siphonCapacity: 100000
    systemMetricsRetention: 7 # Days
    systemMetricsSampling: "*/10 * * * * *" # Every 10 seconds
  ratelimit:
    enabled: true
    maxTokensPerIp: 200
    replenishRate: 10000 # Milliseconds
    retryAfter: 60000 # Milliseconds
  session:
    admin:
      maxSessions: 10
      sessionDuration: 3600 # Seconds
    cleanSchedule: "0 * * * * *" # Every minute
    cookieName: "GattosLabSessionId"
    loginDelay: 500 # Milliseconds
  site:
    cacheDuration: 10080 # Minutes
    root: site
logging:
  level:
    org:
      apache:
      coyote:
        http11:
          Http11Processor: "ERROR"
server:
  compression:
    enabled: false
  connection-timeout: 30000 # Milliseconds
  forward-headers-strategy: "framework"
  http2:
    enabled: true
  max-http-request-header-size: 2048 # Bytes
  shutdown: "graceful"
  tomcat:
    accept-count: 256 # Maximum pending connection queue depth
    max-connections: 8192
    max-keep-alive-requests: 256
    max-swallow-size: 1048576 # Bytes
    processor-cache: 256 # Number of request "processors" to keep cached (to avoid frequent object creation)
spring:
  application:
    name: "Gatto's lab"
  jackson:
    default-property-inclusion: "non_null"
    deserialization:
      fail-on-unknown-properties: true
  jmx:
    enabled: false
  lifecycle:
    timeout-per-shutdown-phase: "15s" # Seconds
  main:
    banner-mode: "off"
  mvc:
    publish-request-handled-events: false
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
debug: true
