serverPort = 443
sslKeyStorePassword = $KEY_STORE_PASSWORD
sslTrustStorePassword = $TRUST_STORE_PASSWORD
allowedOrigins = https://gattoslab.dev,https://www.gattoslab.dev
loginPassword = $LOGIN_PASSWORD
cookieProperties = ; Secure; HttpOnly; Domain=gattoslab.dev; SameSite=Strict; Path=/;
blockedIpV4s = $BLOCKED_IPV4S
blockedIpV6s = $BLOCKED_IPV6S
illegalUserAgentContains = $ILLEGAL_USER_AGENT_CONTAINS
