serverHost = 127.0.0.1
# Ports 443 and 8443 will enable SSL
serverPort = 8080
sslCertificatePath = ./keystore.p12
sslKeyStorePassword = password
keepAliveByDefault = false
allowedOrigins = http://localhost:8080
loginPassword = password
cookieProperties = ;
rateLimitAmount = 500
blockedIpV4s = 99.99.99.0-99.99.99.255,88.88.88.0-88.88.88.255
blockedIpV6s = 4397:d4ce:a7c5:a602:d230:e712:b0c3:0000-4397:d4ce:a7c5:a602:d230:e712:b0c3:ffff,5f03:f707:11fd:67c4:ce34:f1ec:f8a1:0000-5f03:f707:11fd:67c4:ce34:f1ec:f8a1:ffff
illegalUserAgentContains = bad-string,very-bad-string
privilegedStaticResourcePathPrefix = admin/
diskBasedStaticResourcePathSegment = disk/
observabilityDataRetentionDays = 99999
