serverHost = 127.0.0.1
# Ports 443 and 8443 will enable SSL
serverPort = 8080
sslCertificatePath = ./keystore.p12
sslKeyStorePassword = password
keepAliveByDefault = false
allowedOrigins = http://localhost:8080
loginPassword = password
cookieProperties = ;
rateLimitAmount = 500
illegalUserAgentContains = bad-string,very-bad-string
privilegedStaticResourcePathPrefix = admin/
diskBasedStaticResourcePathSegment = disk/
observabilityDataRetentionDays = 99999
