serverHost = 127.0.0.1
# Ports 443 and 8443 will enable SSL
serverPort = 8080
sslCertificatePath = ./keystore.p12
sslKeyStorePassword = password
keepAliveByDefault = true
allowedOrigins = http://localhost:8080
loginPassword = password
cookieProperties = ; Path=/;
rateLimitAmount = 15
illegalUserAgentContains =
privilegedStaticResourcePathPrefix = admin/
diskBasedStaticResourcePathSegment = disk/
observabilityDataRetentionDays = 99999
