app:
  database:
    connectionString: "mongodb://localhost:27017/GattosLabMongoDB"
  session:
    admin:
      apiKey: "test"
      cookieAttributes: "=$; Path=/;"
    cors:
      origins: "http://localhost:8081" #https://localhost:8443
    enabled: true
security:
  require-ssl: false
server:
  port: 8080 #8443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: PKCS12
#    key-alias: http2-alias
